# This is a basic workflow to help you get started with Actions

name: Build APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd IrrigationController/IrrigationController.Android
        msbuild IrrigationController.Android.csproj /verbosity:normal /t:SignAndroidPackage /p:Configuration=Release
    - name: Upload APK
      uses: actions/upload-artifact@v1    
      with:
        name: irrigationcontroller.apk
        path: IrrigationController/IrrigationController.Android/bin/Release/com.companyname.irrigationcontroller-Signed.apk

