# This is a basic workflow to help you get started with Actions

name: Build APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      env:
        Secret_IrrigationServerUrl: ${{ secrets.Secret_IrrigationServerUrl }}
        Secret_GoogleClientId: ${{ secrets.Secret_GoogleClientId }}
        Secret_GoogleClientSecret: ""
        Secret_GoogleRedirectUrl: ${{ secrets.Secret_GoogleRedirectUrl }}
      run: |
        nuget restore
        cd IrrigationController/IrrigationController.Android
        msbuild IrrigationController.Android.csproj /verbosity:normal /t:SignAndroidPackage /p:Configuration=Release
    - name: Upload APK
      uses: actions/upload-artifact@v1    
      with:
        name: irrigationcontroller.apk
        path: IrrigationController/IrrigationController.Android/bin/Release/com.companyname.irrigationcontroller-Signed.apk
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "IrrigationController/IrrigationController.Android/bin/Release/com.companyname.irrigationcontroller-Signed.apk"
        token: ${{ secrets.GITHUB_TOKEN }}

